# -*- coding: utf-8 -*-
"""Wave to txt

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTPLOHlTWV-6lo4MF5zupYx8zcEBXQe-
"""

from scipy.io import wavfile as wav
#from scipy.fftpack import fft
import numpy as np

def wave_to_txt(file1):
  rate, data = wav.read(file1) # put this in the same folder as this code
  np.savetxt("amplitudes.txt", data)
  return data

data = wave_to_txt('sine600hzv1.wav')

def txt_to_wave(file2)
  out_data = np.loadtxt(file2)
  wav.write('scr_output.wav',192000,out_data)
  return out_data

out_data = txt_to_wave('output.txt')



import soundfile as sf

y, sr = sf.read('sine600hzv1.wav', dtype='int16')
np.savetxt("new_amp.txt", y)

sf.write('output.wav',out_data,192000)

wav.write('scr_output.wav',96000,y)

norm_v = (out_data / (np.sqrt(np.sum(np.abs(out_data)))))

sf.write('output.wav',norm_v,192000)

print(max(norm_v))